<?php declare(strict_types=1); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Event Registration | LFCHD</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/css/signup.css" rel="stylesheet"></head><body class="bg-light">
<header class="lfchd-public-header"><div class="container py-3 py-md-4"><div class="d-flex align-items-center gap-3"><img src="/assets/images/lfchd-logo.png" alt="Lexington-Fayette County Health Department" class="lfchd-public-logo"><div><div class="lfchd-public-title h4 mb-0">Lexington-Fayette County Health Department</div><div class="text-muted">Event Registration</div></div></div></div></header>
<main class="container py-4 py-md-5"><div class="row justify-content-center"><div class="col-12 col-lg-9"><div class="card lfchd-page-card"><div class="card-body p-4 p-md-5">
<h1 class="h2 mb-3">LFCHD Event Registration</h1><p class="lead">This system is used by the Lexington-Fayette County Health Department (LFCHD) to register individuals for public health events, appointments, clinics, classes, and related activities.</p><p>If you received a registration link for an LFCHD event, use that link to access the event's registration page.</p>
<h2 class="h4 mt-4">Optional SMS Communications</h2><p>During event registration, you may optionally choose to receive text messages from LFCHD related to that registration. Messages may include registration confirmations, reminders, scheduling information, cancellations, and event-related updates.</p><p>Message frequency varies based on your registration. You may receive <strong>up to 5 SMS messages per event registration</strong>. Message and data rates may apply. Reply <strong>STOP</strong> to opt out or <strong>HELP</strong> for help. Consent to receive SMS messages is optional and is not required to register.</p>
<h2 class="h4 mt-4">Terms &amp; Privacy</h2><p>Use of this registration system is subject to the <a href="/terms">LFCHD Event Registration Terms &amp; Conditions</a>. Information submitted through the system is handled as described in the <a href="/privacy">LFCHD Event Registration &amp; SMS Privacy Policy</a>.</p>
<div class="d-flex flex-column flex-sm-row gap-2 mt-4"><a href="/privacy" class="btn btn-primary">Privacy Policy</a><a href="/terms" class="btn btn-outline-primary">Terms &amp; Conditions</a><a href="/admin" class="btn btn-outline-secondary">LFCHD Staff Login</a></div>
</div></div></div></div></main><footer class="lfchd-footer"><div class="container py-3 text-center small">Lexington-Fayette County Health Department · <a href="/privacy">Privacy Policy</a> · <a href="/terms">Terms &amp; Conditions</a> · <a href="https://www.lfchd.org/" target="_blank" rel="noopener">lfchd.org</a></div></footer><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script></body></html>
