<?php declare(strict_types=1); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Privacy Policy | LFCHD Event Registration</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/css/signup.css" rel="stylesheet"></head><body class="bg-light">
<header class="lfchd-public-header"><div class="container py-3"><div class="d-flex align-items-center gap-3"><img src="/assets/images/lfchd-logo.png" alt="Lexington-Fayette County Health Department" class="lfchd-public-logo"><div><div class="lfchd-public-title h4">Lexington-Fayette County Health Department</div><div class="text-muted">Event Registration &amp; SMS Privacy Policy</div></div></div></div></header>
<main class="container py-4 py-md-5"><div class="row justify-content-center"><div class="col-12 col-lg-9"><div class="card lfchd-page-card"><div class="card-body p-3 p-md-5">
<h1 class="h2 mb-3">Event Registration &amp; SMS Privacy Policy</h1><p class="text-muted">Last updated: September 15, 2026</p>
<p>The Lexington-Fayette County Health Department (LFCHD) uses this event registration system to register individuals for public health events, appointments, clinics, classes, and related activities.</p>
<h2 class="h4 mt-4">Information We Collect</h2><p>Depending on the event, LFCHD may collect information such as your name, email address, mobile phone number, preferred language, selected appointment or event time, and answers to event-specific registration questions.</p>
<h2 class="h4 mt-4">How We Use Information</h2><p>Information submitted through this system is used to administer your registration, communicate information about the event or appointment, provide confirmations and reminders, manage scheduling, and support related LFCHD operations.</p>
<h2 class="h4 mt-4">Mobile Information and SMS Consent</h2><p>If you voluntarily opt in to receive text messages, LFCHD may send registration confirmations, reminders, scheduling information, cancellations, and event-related updates. Message frequency varies based on your registration. You may receive <strong>up to 5 SMS messages per event registration</strong>. Message and data rates may apply. SMS consent is optional and is not required to register for an LFCHD event or appointment.</p>
<p><strong>LFCHD does not share, sell, rent, or provide mobile phone numbers, SMS opt-in information, or messaging consent data to third parties or affiliates for marketing or promotional purposes.</strong></p>
<p>LFCHD may use service providers solely as necessary to operate the registration system and deliver communications on LFCHD's behalf. These service providers may process mobile information only as needed to provide services to LFCHD and are not permitted by LFCHD to use mobile information or SMS consent data for their own marketing or promotional purposes.</p>
<p>You may reply <strong>STOP</strong> to opt out of LFCHD text messages or <strong>HELP</strong> for help. After an opt-out request is processed, LFCHD will not intentionally send additional SMS messages to that mobile number unless the recipient opts in again.</p>
<h2 class="h4 mt-4">Email Communications</h2><p>If you provide an email address, LFCHD may use it to send registration confirmations, reminders, cancellations, and event-related information.</p>
<h2 class="h4 mt-4">Information Sharing</h2><p>LFCHD does not sell registration information. Non-SMS registration information may be shared with authorized LFCHD personnel and service providers when necessary to operate the registration system, deliver communications, provide the registered service, comply with applicable law, or protect LFCHD systems and operations. The restrictions above apply to mobile phone numbers, SMS opt-in information, and messaging consent data.</p>
<h2 class="h4 mt-4">Data Security and Retention</h2><p>LFCHD uses reasonable administrative and technical safeguards to protect information submitted through this system. Information may be retained as needed for operational, legal, records-management, and public-health purposes.</p>
<h2 class="h4 mt-4">Terms &amp; Conditions</h2><p>Additional information about the LFCHD event registration SMS program is available in our <a href="/terms">Terms &amp; Conditions</a>.</p>
<h2 class="h4 mt-4">Contact</h2><p>Questions regarding this registration system or privacy policy may be directed to LFCHD using the contact information published on <a href="https://www.lfchd.org/" target="_blank" rel="noopener">lfchd.org</a>.</p>
<hr class="my-5"><h1 class="h2 mb-3" lang="es">Política de privacidad de registro de eventos y SMS</h1><p lang="es">El Departamento de Salud del Condado de Lexington-Fayette (LFCHD) utiliza este sistema para registrar a las personas en eventos, citas, clínicas, clases y otras actividades de salud pública.</p><h2 class="h4 mt-4" lang="es">Información móvil y consentimiento para SMS</h2><p lang="es">Si acepta voluntariamente recibir mensajes de texto, LFCHD puede enviar confirmaciones de registro, recordatorios, información de programación, cancelaciones y actualizaciones relacionadas con el evento. La frecuencia de los mensajes varía según su registro. Puede recibir <strong>hasta 5 mensajes SMS por cada registro de evento</strong>. Pueden aplicarse tarifas de mensajes y datos. El consentimiento para recibir SMS es opcional y no es necesario para registrarse.</p><p lang="es"><strong>LFCHD no comparte, vende, alquila ni proporciona números de teléfono móvil, información de suscripción a SMS ni datos de consentimiento de mensajería a terceros o afiliados con fines de mercadeo o promoción.</strong></p><p lang="es">Responda <strong>STOP</strong> para dejar de recibir mensajes de texto de LFCHD o <strong>HELP</strong> para obtener ayuda.</p>
<div class="mt-4"><a href="/" class="btn btn-outline-primary">Return to LFCHD Event Registration</a></div></div></div></div></div></main><footer class="lfchd-footer"><div class="container py-3 text-center small">Lexington-Fayette County Health Department · <a href="/privacy">Privacy Policy</a> · <a href="/terms">Terms &amp; Conditions</a></div></footer><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script></body></html>
